### ISSUE TITLE
App closing/stopping when closing Show Progress window

### ISSUE THREAD

**Issue by dw-andrewsfasteners** [DRN88/HotFolderPrinterFoxitPdf#2]
Hi,
Unsure if thats easy to fix or not. 

When App is run through `dotnet run` and is in tray, when you right click and select Show Progress window, to close this window you using X button. This shall only close the Show Progress window but instead is stopping the whole app.

**Comment by DRN88** [comment]
"Show Progress" is actually the main form, so it closes it. We need handle this in FormClosing event it differently. Rebuilt and sent it to you.

```c#
        private void frmMainForm1_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (e.CloseReason == CloseReason.UserClosing)
            {
                e.Cancel = true;
                Hide();
            }
        }
```

**Comment by dw-andrewsfasteners** [comment]
Super, thank you.
